### ISSUE TITLE
build fails without Cargo.lock

### ISSUE THREAD

**Issue by muhamadazmy** [scs/substrate-api-client#110]
If Cargo.lock is deleted, or the module is imported in another crate, it does not build with this error:

```
rror[E0603]: module `export` is private
   --> /home/azmy/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-multiaddr-0.9.6/src/onion_addr.rs:3:12
    |
3   | use serde::export::Formatter;
    |            ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/azmy/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.119/src/lib.rs:275:5
    |
275 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by brenzi** [comment]
You have to make sure that Cargo.lock only contains a single commit of substrate. the api-client is only tested against exactly the upstream commit stated in its toml files. You can try to patch dependencies if there are no breaking changes upstream

**Comment by muhamadazmy** [comment]
Thank you @brenzi  for your answer

**Comment by brenzi** [comment]
It can be tricky. We can't even guarantee that it will work if you use the same substrate commit, because non-substrate crates might've been updated and break things. This can only be avoided by keeping the Cargo.lock once you have a working setup. Usually, parity is quick in fixing these things, but then we'd have to upgrade api-client too...it's all still a moving target...

If you want to upgrade substrate dependencies, we're happy to take a PR
