### ISSUE TITLE
Cargo update not possible due to no substrate version specified

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#141]
The same issue as in https://github.com/integritee-network/sgx-runtime/issues/16

This could be fixed by adding `version = 3.0.0` to substrate  depedencies. Or wait until substrate removes the -dev.

**Comment by ivanceras** [comment]
Hi guys, I've been playing with this library and it is great with. It has lots of examples and easy to get into.
However, the published version of this crate is developed against the master branch of substrate. This can lead to breakage in the code when other people is using this library.

It would be nice to develop against a specific version of substrate library that is already published in crates.io. The version 3.0.0 is out. The other alternative is to use a specific monthly tag ie: `monthly-2021-07`, same to the substrate.dev/tutorials.

**Comment by clangenb** [comment]
I see this becoming a topic more and more. We decided to use to `branch = master` as this was in mandatory for parachain development because branch used `branch = ...`. But now it seems the community is using our lib more and more, which I am happy about. So, we should also supply an alternate option that uses pinned releases of substrate. I will look into that @ivanceras

**Comment by haerdib** [comment]
So I guess it would make sense to feature a "release" branch that tags different substrate versions.
