### ISSUE TITLE
`send_extrinsic` should return a hash for all `XtStatus` variants.

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#175]
#169 introduces a new `XtStatus` to spam tx's even faster. However, the json-rpc interface does not return an xt-hash here.

We should calculate the xt-hash ourselves in that case. However, the stringified interface of `send_extrinsic` makes this a bit tedious. It will get very easy if we change that interface.

So to change that we need:
* change `send_extrinsic` signature to: `send_extrinsics<XT: HexEncode>(xt: XT, exit_on: XtStatus, ...)`
* implement `fn hash(&self) -> H256` for `UncheckedExtrinsicV4`
* return `xt.hash()` in send_extrinsic if the `exit_on == XtStatus::SubmitOnly`

**Comment by clangenb** [comment]
I have just seen that other variants don't return a hash either, so we should implement it for all of those method.

**Comment by haerdib** [comment]
Well, I guess our documentation in the code is quite lacking. It seems that the hash returned by `send_extrinsic` is not the transaction hash, but the block hash where the tx got included. That's why only `Finalized` and `InBlock` return an hash.

To test that, I added an error log and let it run in CI (https://github.com/scs/substrate-api-client/actions/runs/3445270889/jobs/5748935375): 
```
[2022-11-11T13:24:23Z ERROR substrate_api_client::std::rpc::ws_client] parsing {"jsonrpc":"2.0","result":"yqRsqZekaueWccbX","id":"3"}
437d1f127e74   parity/substrate:latest   "/usr/local/bin/subs…"   26 seconds ago   Up 25 seconds   0.0.0.0:9933->9933/tcp, :::9933->9933/tcp, 0.0.0.0:9944->9944/tcp, :::9944->9944/tcp, 0.0.0.0:30333->30333/tcp, :::30333->30333/tcp   awesome_mestorf
Interacting with node on ws://127.0.0.1:9944

signer account: 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
[+] Bob's Free Balance is is 1000000000000000000000

Sending an extrinsic from Alice (Key = 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY),

to Bob (Key = 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty)

[2022-11-11T13:24:23Z ERROR substrate_api_client::std::rpc::ws_client] parsing {"jsonrpc":"2.0","method":"author_extrinsicUpdate","params":{"subscription":"yqRsqZekaueWccbX","result":"ready"}}
[2022-11-11T13:24:24Z ERROR substrate_api_client::std::rpc::ws_client] parsing {"jsonrpc":"2.0","method":"author_extrinsicUpdate","params":{"subscription":"yqRsqZekaueWccbX","result":{"inBlock":"0x09fea9ae0b98ab2e6d1404990efcb0ea133da95a7cdf6d131b292f8b5835b89c"}}}
[+] Composed extrinsic: UncheckedExtrinsic(Some((MultiAddress::Id(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), SubstrateDefaultSignedExtra { era: Era::Immortal, nonce: 0, tip: AssetTip { tip: 0, asset: None } })), ([6, 0], MultiAddress::Id(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (5FHneW46...)), 1000000000000))

[+] Transaction got included. Hash: Some(0x09fea9ae0b98ab2e6d1404990efcb0ea133da95a7cdf6d131b292f8b5835b89c)

[+] Bob's Free Balance is now 1000000001000000000000

```

Emphasizing:
`[2022-11-11T13:24:24Z ERROR substrate_api_client::std::rpc::ws_client] parsing {"jsonrpc":"2.0","method":"author_extrinsicUpdate","params":{"subscription":"yqRsqZekaueWccbX","result":{"inBlock":"0x09fea9ae0b98ab2e6d1404990efcb0ea133da95a7cdf6d131b292f8b5835b89c"}}}`
and the returned hash:
`[+] Transaction got included. Hash: Some(0x09fea9ae0b98ab2e6d1404990efcb0ea133da95a7cdf6d131b292f8b5835b89c)`


So I don't think we can solve this issue. But we should adapt our code documentation. What do you think?
