### ISSUE TITLE
Support asset transaction payment

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#211]
The api client currently only supports `pallet_transaction_payment::ChargeTransactionPayment` as `SignedExtra`.

However, it should also be possible to send extrinsic with the `pallet_asset_tx_payment::ChargeAssetTxPayment<Runtime>` in the `SignedExtra`.

https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/asset-tx-payment/src/lib.rs

**Comment by clangenb** [comment]
This will be a call to make the api-client more generic, so that the signed extra is configurable along with other params.

**Comment by clangenb** [comment]
There is a proof of concept that worked with encointer after introducing community-currency fees on branch: https://github.com/scs/substrate-api-client/tree/cl/encointer-community-currency-fees-hotfix

Crucial change: https://github.com/scs/substrate-api-client/blob/b51d802b054bbd655b3178448822e2db04a8a71e/primitives/src/extrinsic_params.rs#L21

To generically introduce this as a generic option in the api-client I suggest giving the api-client an additional type parameter:
`ExtrinsicParamBuilder<ExtrinsicParams>`, similar to how they do it in [subxt](https://github.com/paritytech/subxt/blob/9330ba067d1edf90c04493b4e5b88e54124758fc/subxt/src/extrinsic/params.rs).

We would modify the `Api` such that it looks like:

```
pub struct Api<WsClient, ExtrinsicParamsBuilder: ExtrinsicsParamBuilder> {

     .....
     extrinsics_params_builder: Option<ExtrinsicsParamBuilder>

}
```

The `extrinsics_params_builder` is optional because it can then be used in the compose macros with `unwrap_or_default`. Where the `default` is an absolute valid choice, which will implement the same parameters as in [subxt](https://github.com/paritytech/subxt/blob/9330ba067d1edf90c04493b4e5b88e54124758fc/subxt/src/extrinsic/params.rs#L136).
