### ISSUE TITLE
Fetching actual storage map keys.

### ISSUE THREAD

**Issue by TJ-alchemist** [scs/substrate-api-client#234]
**Intention**: Want to work with keys of a storage map.
I have used the method **[get_storage_map_key_prefix](https://docs.rs/substrate-api-client/0.6.6/substrate_api_client/struct.Api.html#method.get_storage_map_key_prefix)** to fetch the **StorageKey**, then used the **[get_keys](https://docs.rs/substrate-api-client/0.6.6/substrate_api_client/struct.Api.html#method.get_keys)** method for fetching the keys.
But what i am getting are hash values of all the keys of the storage map. 
I want to work with the actual keys.
Is there a way possible?

**Comment by clangenb** [comment]
Here I am a bit confused, to my knowledge, the keys are always a concatenation of hashes, there are no unhashed keys. Am I missing something?

**Comment by TJ-alchemist** [comment]
I am using a storage map for a substrate node. 
The key is an integer and value is a struct.
I actually wanted to access the same keys that are being stored inside the storage.
Like for example,
My key is "10" and the value corresponding to this key is a struct.
So what I want is that it should return the value "10" as my key, rather than the hash of "10".

**Comment by clangenb** [comment]
Hmmm, I am uncertain if this is possible. Because the storage keys returned there are the concatenation of hashes, see https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/.

So you cannot extract the underlying key because hashes can only be computed one way.

There might be another rpc, that does what you want, but I am unware of that.

**Comment by clangenb** [comment]
I take your 👍 that you are satisfied with the answer and I will close the issue. :)
