### ISSUE TITLE
couldn't decode event record list

### ISSUE THREAD

**Issue by macrocan** [scs/substrate-api-client#265]
Error occur when  run example example_event_callback in matser branch: 
`
cargo run --example example_event_callback -- -u wss://rpc.polkadot.io -p 443
`

**Comment by clangenb** [comment]
It is expected that some events can't be decoded because we try to decode here into the events from the substrate-node-template runtime: https://github.com/scs/substrate-api-client/blob/ab586d8be719243aa29503ec8c7b1457b2cd0830/examples/example_event_callback.rs#L50

As the polkadot-runtime looks different from the template, there are discrepancies in the event format.
