### ISSUE TITLE
There seems to be an error when sending the transaction

### ISSUE THREAD

**Issue by CoderfishGzh** [scs/substrate-api-client#343]
When I execute the example of the trade function, an error occurs. What do I need to do to solve this problem

```
    Finished dev [unoptimized + debuginfo] target(s) in 3.63s
     Running `target/debug/rust-substrate`
[+] Composed Extrinsic:
 UncheckedExtrinsic(Some((MultiAddress::Id(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...)), SubstrateDefaultSignedExtra { era: Era::Immortal, nonce: 0, tip: AssetTip { tip: 0, asset: None } })), ([8, 0], 10))

[+] Transaction got included. Hash: Err(RpcClient(Extrinsic("extrinsic error code 1002: Verification Error: Runtime error: 
Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Invalid length prefix: 
RuntimeApi(\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Invalid length prefix\")")))
```

**Comment by CoderfishGzh** [comment]
Is it a problem with my substrate version?

**Comment by haerdib** [comment]
Hm.. No, I don't think that's the substrate version. More like a mismatch between types. I'm not sure which example exactly you're using, but currently all examples are matched to the `kitchensink_runtime`. Which means they are using `AssetTipExtrinsicParams`, e.g. they depend upon the `asset` pallet. Is your runtime perhaps using the balances pallet? If so, try using `PlainTipExtrinsicParams` instead of `AssetTipExtrinsicParams` here:

https://github.com/scs/substrate-api-client/blob/31a91d645aa542edd5d013ed1f4edc6b446cdfb3/examples/example_transfer_using_seed.rs#L41-L43

**Comment by haerdib** [comment]
I'm currently thinking of a totally different solution: https://github.com/scs/substrate-api-client/issues/344#issuecomment-1328652771

Maybe you know the answer to that: Is is possible to detect which tips to use, if the `Runtime` is known?

**Comment by haerdib** [comment]
#344 seems certainly possible, but it will take some time. I looked into the docker problem, but it seems parity does not upload the substrate node-template anymore (checked https://hub.docker.com/u/parity/),

**Comment by haerdib** [comment]
Closing this in favour of #383
