### ISSUE TITLE
Do not use wildcard pub re-export

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#430]
This can easily lead to exports of the same named struct, such as  `Error` and co (see https://github.com/scs/substrate-api-client/pull/424#discussion_r1063263704). 

A cleaner way would be to re-export everything that should be public specifically.

**Comment by clangenb** [comment]
When I tried to integrate the refactored api-client into the worker, I thought that the exports are in general kind of a chaos.

**Comment by echevrier** [comment]
Check wildcard re-export :
- check that the new path is unique, at every export level (no conflict with another item from other modules)
- check the visibilty of the item

src/lib.rs : the root package
```
pub use ac_compose_macros::*;
pub use ac_node_api::*;
pub use ac_primitives::*;
pub use api::*;
```

1. **ac_compose_macros**
  compose_macros/src/lib.rs
  - `pub use rpc::*;`  Visible OK. Name conflict: NO
- re-export of `ac_compose_macros` is OK :
     - All Items' paths are well defined (no conflict with another item from other modules) 
     - All Items should be visible
- public API : `substrate_api_client::compose_extrinsic` instead of `substrate_api_client::ac_compose_macros::compose_extrinsic` 
  
2. **ac_node_api**
  node-api/src/lib.rs:
    - `pub use decoder::*;` Visible OK. Name conflict: NO.
    - `pub use events::*;` Visible OK. Name conflict: NO.
    - `pub use metadata::*;` Visible OK. Name conflict: NO.
    - `pub use storage::*;` Visible OK. Name conflict: NO.
 - re-export of `ac_node_api` is OK :
     - All Items' paths are well defined (no conflict with another item from other modules) 
     - All Items should be visible
- public API : 

  - `substrate_api_client::Metadata` instead of `substrate_api_client::ac_node_api::metadata::Metadata` or  `substrate_api_client::ac_node_api::Metadata` 

  - `substrate_api_client::TypeId` instead of  `substrate_api_client::ac_node_api::decoder::TypeId` or `substrate_api_client::ac_node_api::TypeId` 
  - `substrate_api_client::TypeId` instead of  `substrate_api_client::ac_node_api::events::Events` or `substrate_api_client::ac_node_api::Events` 
  - `substrate_api_client::StorageValue` instead of  `substrate_api_client::ac_node_api::storage::StorageValue` or `substrate_api_client::ac_node_api::StorageValue` 

3. **ac_primitives**
  primitives/src/lib.rs:
  - `pub use extrinsic_params::*;` Visible OK. Name conflict: NO 
  - `pub use extrinsics::*`; Visible OK. Name conflict: NO 
  -` pub use pallet_traits::*`; Visible OK. Name conflict: NO 
  - `pub use rpc_numbers::*`; Visible OK. Name conflict: NO 
  - `pub use serde_impls::*`;  Visible OK. Name conflict: NO 
  - `pub use signer::*`; Visible OK. Name conflict: NO 
  - `pub use types::*`; Visible OK. Name conflict: NO 


5. **api**

**Comment by echevrier** [comment]
Check: src/rpc/mod.rs 

- `pub use ws_client::*;` Visible OK. Name conflict: NO
- `pub use tungstenite_client::*;`  Visible OK. Name conflict: NO
- `pub use jsonrpsee_client::*;` Visible OK. Name conflict: NO
- `pub use error::*;` Visible OK. Name conflict: NO

- public API : 
  - `substrate_api_client::rpc::Error` instead of substrate_api_client::rpc::error:Error`
  - `substrate_api_client::rpc::WsRpcClient` instead of substrate_api_client::rpc::ws_client::client::WsRpcClient`
  - `substrate_api_client::rpc::TungsteniteRpcClient` instead of substrate_api_client::rpc::tungstenite_client::client::TungsteniteRpcClient`
  - `substrate_api_client::rpc::JsonrpseeClient` instead of substrate_api_client::rpc::jsonrpsee_client::JsonrpseeClient`
  
**Note**:
JsonrpseeClient API:
- substrate_api_client::rpc::JsonrpseeClient
- substrate_api_client::rpc::SubscriptionWrapper
  
WsRpcClient API:
- substrate_api_client::rpc::WsRpcClient
- substrate_api_client::rpc::subscription::WsSubscriptionWrapper

TungsteniteRpcClient API:
- substrate_api_client::rpc::TungsteniteRpcClient` 
- substrate_api_client::rpc::TungsteniteSubscriptionWrapper`
