### ISSUE TITLE
Derive decode for `Bytes`

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#456]
Not 100% sure though I it is needed, but currently I need to do for a set of encoded extrinsics:

 ```rust 

let xts: Vec<Vec<u8>> = Decode::decode(&mut bytes).unwrap();
for xt in xts {
   api.submit_and_watch_opaque_xt_unit(xt.into(), XtStatus::InBlock);
}
```

**Comment by haerdib** [comment]
Why not simply take the inner value of Bytes? E.g. `bytes.0`?

**Comment by clangenb** [comment]
It is about decode not encode, but yeah I am not sure if we need this. We could also stick to using vec, and just call `vec.into()` when we pass it into the function.

**Comment by haerdib** [comment]
Not sure if I understand the problem. So what you want isn't: 

 ```rust 
// Access encoded Vec<u8> via bytes.0:
let xts: Vec<Vec<u8>> = Decode::decode(&mut bytes.0.as_slice()).unwrap();
for xt in xts {
   api.submit_and_watch_opaque_xt_unit(xt.into(), XtStatus::InBlock);
}
```

But if you think it will help, a Decode impl for easy inner Vec<u8> access should not be a problem to implement.

**Comment by haerdib** [comment]
The reason I'm hesitating is, that I hope, that somewhen in the future, the api client does not need to reimplement Bytes. And substrate does not offer Decode for Bytes either. Which would then result in a breaking change.

**Comment by haerdib** [comment]
I'm closing this issue for now because Bytes is a simple wrapper struct needed for hex serializing. If the inner (encoded) Vec needs to be accessed, a `bytes.0` should do it:

https://github.com/scs/substrate-api-client/blob/116b3e69bc94cdd7a397bccbbee4fc4666f02bdc/src/api/api_client.rs#L251-L254
Also, there is no api-client function that returns a `Bytes` type. This will only be used by advanced users that directly access the rpc-client.

Since Bytes is originally a substrate type and is only defined here out of necessity, I don't think we should add extra functionalities, that substrate does not.
