### ISSUE TITLE
Introduce chain api helpers

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#496]
E.g. `last_finalized_block`, `get_genesis_hash`, `get_blocks`. I think these are standard functionalities and should be offered by the api-client.

See worker implementation: https://github.com/integritee-network/worker/blob/master/core-primitives/node-api/api-client-extensions/src/chain.rs

**Comment by Niederb** [comment]
The implementation of `get_blocks` is complicated by the fact that `BlockNumber` is not necessarily a number. We cannot easily create a Range from it. See:
https://github.com/integritee-network/worker/blob/6c84d2c76c13be162afe2607d1a1ef5b01707c6f/core-primitives/node-api/api-client-extensions/src/chain.rs#L77
Some options:
- Restrict `BlockNumber` to implement the Step trait (nightly only feature)
- Pass in a slice of `BlockNumber` instead of start/end
I think I would go for the slice as it allows for different use cases as well. @haerdib What do you think?

**Comment by haerdib** [comment]
Yes, I'd also vote for the slice. I'd rather not enforce more traits than substrate does, as this would risk incompatibility in some cases.
