### ISSUE TITLE
Improve decoding of `EventDetails` and `DispatchErrors`

### ISSUE THREAD

**Issue by echevrier** [scs/substrate-api-client#564]
Similar to subxt, use [scale-decode](https://github.com/paritytech/scale-decode) and [scale-encode](https://github.com/paritytech/scale-encode/blob/main/scale-encode/src/lib.rs) :
- more flexible to substrate changes( new variant, indexes changes, ...)
- using the visitor seems to allow zero-copy decoding.

These libraries need to be made no-std compatible.

Replace the [decoder ](https://github.com/scs/substrate-api-client/tree/master/node-api/src/decoder).

Rework [EventDetails](https://github.com/scs/substrate-api-client/blob/e1c766cb9312cedd40f024d8e4a1d955abc8ab1c/node-api/src/events.rs#L156) and [Dispatch Errors](https://github.com/scs/substrate-api-client/blob/e1c766cb9312cedd40f024d8e4a1d955abc8ab1c/node-api/src/error.rs#L91) decoding

**Comment by haerdib** [comment]
I've looked a bit into this issue and I think the subxt version, while it does contain a less code duplication, is not that much more flexible than the current solution (check out https://github.com/paritytech/subxt/blob/f344d0dd4d96c4b6398900a40546ec6660a8134a/subxt/src/error/dispatch_error.rs#L216-L230 &  https://github.com/paritytech/subxt/blob/f344d0dd4d96c4b6398900a40546ec6660a8134a/subxt/src/error/dispatch_error.rs#L267-L280)
If Substrate types changes, so does our and the code of subxt.

What I do see, however, is the usage of the Visitor, to avoid needless copying. That would be an optimization, rather than require less code changes in case of breaking changes on Substrate side.

What do you think?

**Comment by masapr** [comment]
If that's the case, then we should do this only if the effort is <2-3 days.
