### ISSUE TITLE
Support system_accountNextIndex RPC

### ISSUE THREAD

**Issue by zTgx** [scs/substrate-api-client#572]
We currently have an [issue ](https://github.com/litentry/litentry-parachain/issues/1425) regarding `accountNextIndex` and the system API [link ](https://polkadot.js.org/docs/kusama/rpc/#accountnextindexaccountid-accountid-index) is provided here. We are currently using substrate-api-client with polkadot-v0.9.39-tag-v0.7.0, which does not have the `system_accountNextIndex` RPC. So, I would like to ask, do you have any plans to include this RPC in which version? Thank you!

**Comment by haerdib** [comment]
Hey @zTgx 

I introduced the new function in this PR: https://github.com/scs/substrate-api-client/pull/573/files, so it should be available in the next version (e.g. polkadot v0.9.43 hopefully)

But since you're using quite an outdated version, you have two options:
1. update to a newer version. Check out https://github.com/scs/substrate-api-client#example-upgrades-from-older-to-newer-versions for an example upgrade (and the necessary changes involved) in the Integritee worker. If you experience problems with that, feel free to ask right away. I'm sure other projects will profit from this as well.
2. Implement the api function for the respective branch yourselves. While we don't update old versions, a PR (given it is backward compatible) on the respective branch will be accepted. Introducing a function in [this file](https://github.com/scs/substrate-api-client/blob/84af198434ea210eb0cd90cb8239748c376a079a/src/std/rpc/json_req.rs) should suffice. I imagine something like this could work:
```rust
pub fn system_account_next_index(account_id: AccountId32) -> Value {
	json_req("system_accountNextIndex", vec![to_value(account_id).unwrap()], 1)
}
```

I hope this helps you :)

**Comment by zTgx** [comment]
Thank you for your reply. It has been very helpful to me.
