### ISSUE TITLE
Investigate: Rename `SubstrateKitchensinkConfig` to something more generic

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#586]
From https://github.com/encointer/encointer-node/pull/328#discussion_r1229303759:

>But it seems to be generic enough such that it works for us too. So it could be something like `DefaultAssetRuntimeConfig`.

I agree with that line of thought. SubstratKitchensinkConfig is correct. But maybe a little too confining.

**Comment by echevrier** [comment]
According to Substrate, the node example runtime is NOTHING production-like, and should not be used, nor inspired from ;) That's why they've renamed the node-runtime to node-kitchensink-runtime. 
Changing the name of our configuration is then deceptively reassuring,  but I can understand, that for live nodes, referring to a Kitchensink is not so nice.

We have another config  that is compatible with a polkadot node: [PolkadotConfig  ](https://github.com/scs/substrate-api-client/blob/master/primitives/src/config/polkadot.rs#L16C18-L16C18). If we rename SubstratKitchensinkConfig without reference to Substrate, we should also rename PolkadotConfig.

A little too confining? I'm not sure where to put the emphasis. For the moment the differences between the configs are the methods of payment or the nodes that use them. If we don't want to make any reference to node-kitchensink-runtime, I'd like to remain as neutral as possible. So maybe DefaultAssetRuntimeConfig instead of SubstratKitchensinkConfig and DefaultRuntimeConfig instead of PolkadotConfig?

Other possibilities 
- DefaultSubstrateAssetRuntimeConfig and DefaultPolkadotRuntimeConfig? 
- SubstrateAssetRuntimeConfig and PoladotRuntimeConfig?

@haerdib , @clangenb What do you think?

**Comment by clangenb** [comment]
Yes, I can understand the rationale why they renamed it into the kitchensink runtime. However, if the config works for polkadot and kusama, I think it shouldn't have the kitchensink name in it. I can agree with your second set of suggestions, but would like to add some more variants:

* `AssetRuntimeConfig`, `PolkadotConfig`

I don't have a strong tendency towards your or mine suggestions.

**Comment by haerdib** [comment]
Maybe I'm a little behind here, but for me, the difference between `Polkadot` and `Substrate` is not clear in regard to the config. Both, Substrate and Polkadot nodes may have both types of Payments, and both, substrate-node-template (not kitchsink-runtime, as @echevrier noted should not be used as template), and polkadot nodes by default use plain tip. 

Maybe I'm wrong here? But if not, I'd refrain from using Polkadot or Substrate in the naming, but instead focus on `Asset` and `Plain` or `Default` ?

Suggestions:
-` AssetConfig`, `PlainConfig`
- `DefaultAssetConfig`, `DefaultConfig`
- `AssetRuntimeConfig`, `RuntimeConfig`

**Comment by echevrier** [comment]
So let's go with  DefaultAssetConfig and DefaultPlainConfig. Emphasis on Default and on Asset/Plain.

**Comment by clangenb** [comment]
I think asset and plain are a bit too mysterious. As a slight adjustment, I would suggest:

`DefaultAssetPaymentConfig`, `DefaultNativePaymentConfig` although I am not sure about the latter. :)

**Comment by clangenb** [comment]
Yes, I think this is OK, I can agree with your suggestions. My primary concern before was that `PlainTip` has been coined by subxt, and is not a term known to the general substrate/polkadot dev.

**Comment by echevrier** [comment]
`AssetPaymentConfig`, `DefaultPaymentConfig `sounds like payment configs. I would prefer `AssetRuntimeConfig `and `DefaultRuntimeConfig `if we can't use Plain.

**Comment by clangenb** [comment]
Sounds good to me!

**Comment by haerdib** [comment]
Yes, that makes sense 👍
