### ISSUE TITLE
how to treat custom types in events?

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#76]
We have the issue that our SubstraTEE-client needs to decode custom types in events.

A workaround is this:
https://github.com/scs/substrate-api-client/blob/ea4192357ddc02bf05c0218e24026b2419289228/src/events.rs#L101

this does work but we don't want to insert custom types here.
Could we leave the decoding to the user?

**Comment by clangenb** [comment]
Yes, agreed.

The problem is rather (not 100% sure atm) that decoding vector `Vec::<frame_system::EventRecord<Event, Hash>>` is screwed up if there are unknown types.

However,  `decoder.register_type_size`  is public. Primitives can easily be added by the user by just calling the method on the decoder that is returned by `EventDecoder::try_from(metadata)` to add an extra type. 

Which means, we need to rewrite the workflow such that the user has access to the decoder, which is now hidden in the `api.wait_for_event` method. But this can be easiliy done.

I am unsure what problem the following poses:

 ```
pub struct Request {
    pub shard: ShardIdentifier,
    pub cyphertext: Vec<u8>,
}
```

have you tried it with your workaround, does it work?

**Comment by brenzi** [comment]
haven't tried `Request`

**Comment by kylezs** [comment]
What is the recommended solution to this now? If I want to decode custom events from custom pallets?

**Comment by clangenb** [comment]
This is how we do it: https://github.com/scs/substraTEE-worker/blob/e2619abfff07a2fd9054fcbd4e23879cc0d0eba3/client/src/main.rs#L554

Structs are currently not supported.

You could also import the runtime's events as we do it in the example. But (I believe this is still true) importing the runtime types cannot be done independently of the runtime itself, which leads to a lot of code-bloat you import.
